# Jenkins
jenkins_hostname: jenkins.example.com

# Config for DigitalOcean.
private_key_path: "~/.ssh/id_rsa"
digital_ocean_token: "CHANGEME"
digital_ocean_image: "ubuntu-16-04-x64"
digital_ocean_region: "nyc3"
digital_ocean_size: "512mb"
digital_ocean_ssh_key_name: "CHANGEME"
