---
- name: Ensure necessary groups exist.
  group: "name={{ item }} state=present"
  with_items:
    - admin

- name: Add a admin user.
  user: "name=admin shell=/bin/bash groups=admin password={{ admin_password }} update_password=on_create"

- set_fact:
    my_ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

- name: Add public key to admin user
  authorized_key: user=admin key="{{ lookup('file', my_ssh_key) }}"
